[package]
name = "flash-lso"
version = "0.3.1"
authors = ["CUB3D <callumthom11@gmail.com>"]
description = "Fast and safe SOL/AMF0/AMF3 format parsing. Supports serde, Adobe flex and cyclic references"
repository = "https://github.com/CUB3D/rust-sol"
readme = "README.md"
license = "MIT"
keywords = ["sol", "amf", "parser", "serializer", "flash"]
edition = "2018"
categories = ["data-structures", "encoding", "parser-implementations"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
cookie-factory = "0.3.1"

serde = { version = "1", optional = true, features = ["derive", "rc"] }

derive-try-from-primitive = "1.0.0"

enumset = { version = "1.0.0", features = ["serde"] }

[dev-dependencies]
pretty_assertions = "0.6.1"

[features]
default = []
flex = []
all = ["flex", "serde"]
